Functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просмпотривать товары и посматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
Non-functional:
  - Вэб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Веб-сайт должен быть безопасным и защищать данные пользователя
  - Веб-сайт должен иметь мобильную версию
  - Веб-сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Веб-сайт должен быть способен обрабатывать большое количество трафика
  - Веб-сайт должен быть доступен на различных устройствах
Implicit:
  - Веб-сайт должен быть разработан как SPA приложение, которое не перезагружает страницу
  - На странице товара и в катологе отрображаются название, рейтинг и цена (со скидкой/без скидки)
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в катологе, оформить заказ с переходом на страницу оплаты
  - Корзина должнв хранится в сессии браузера
